"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";

const roles = ["Software Engineer", "Frontend Developer", "AI Engineer", "Data Analyst"];
type TimeLeft = { days: number; hours: number; minutes: number; seconds: number };

function CountUpStat({ value, suffix = "", label }: { value: number; suffix?: string; label: string }) {
  const [count, setCount] = useState(0);
  const [started, setStarted] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      if (!entry.isIntersecting || started) return;
      setStarted(true);
      const start = performance.now();
      const frame = (now: number) => {
        const progress = Math.min((now - start) / 900, 1);
        setCount(Math.round(value * (1 - Math.pow(1 - progress, 3))));
        if (progress < 1) requestAnimationFrame(frame);
      };
      requestAnimationFrame(frame);
    }, { threshold: 0.3 });
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [started, value]);
  return <div ref={ref}><p className="text-3xl font-semibold tracking-[-0.04em] text-white">{count}{suffix}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>;
}

function ArrowIcon() {
  return <svg aria-hidden="true" className="h-4 w-4" viewBox="0 0 20 20" fill="none"><path d="M4 10h11M11 5l5 5-5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

export default function ABTalksLanding() {
  const [roleIndex, setRoleIndex] = useState(0);
  const [timeLeft, setTimeLeft] = useState<TimeLeft>({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  useEffect(() => {
    const interval = window.setInterval(() => setRoleIndex((current) => (current + 1) % roles.length), 2600);
    return () => window.clearInterval(interval);
  }, []);
  useEffect(() => {
    const deadline = new Date("2026-10-01T00:00:00+05:30").getTime();
    const timer = window.setInterval(() => {
      const distance = Math.max(deadline - Date.now(), 0);
      setTimeLeft({ days: Math.floor(distance / 86_400_000), hours: Math.floor((distance / 3_600_000) % 24), minutes: Math.floor((distance / 60_000) % 60), seconds: Math.floor((distance / 1_000) % 60) });
    }, 1000);
    return () => window.clearInterval(timer);
  }, []);

  const steps = [["01", "Build deliberately", "Work through a focused daily brief designed to compound into tangible skills."], ["02", "Publish your proof", "Turn your GitHub activity and project updates into a body of work recruiters can inspect."], ["03", "Get career-ready", "Receive a portfolio with context, consistency, and the confidence to show it."]];
  const tracks = ["Full-stack engineering", "Frontend & product", "AI & machine learning", "Data & analytics", "Backend systems", "DSA & problem solving"];
  const testimonials = [["RS", "Rahul S.", "NIT Trichy", "The programme gave me a structure I could actually sustain. By week five, I had three projects and an internship offer."], ["PM", "Priya M.", "BITS Pilani", "The daily public progress kept me accountable. It made interview conversations much easier because I had real work to discuss."]];

  return <main className="min-h-screen overflow-hidden bg-[#090b12] text-white selection:bg-orange-400 selection:text-[#090b12]">
    <style dangerouslySetInnerHTML={{ __html: `@keyframes float {0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}} @keyframes rise {from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}} .role-rise{animation:rise .35s ease-out both}.orb-float{animation:float 7s ease-in-out infinite}` }} />
    <div className="pointer-events-none absolute inset-x-0 top-0 h-[620px] bg-[radial-gradient(ellipse_at_top,rgba(249,115,22,0.16),transparent_62%)]" />
    <div className="pointer-events-none absolute right-[-150px] top-[380px] h-80 w-80 rounded-full bg-orange-500/10 blur-[110px] orb-float" />
    <nav className="relative mx-auto flex max-w-6xl items-center justify-between px-6 py-5 lg:px-8"><Link href="/" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-orange-500 text-sm font-black text-[#090b12]">A</span><span>ABTalks</span></Link><div className="hidden items-center gap-7 text-sm text-slate-400 md:flex"><a href="#how-it-works" className="transition-colors hover:text-white">How it works</a><a href="#tracks" className="transition-colors hover:text-white">Tracks</a><a href="#outcomes" className="transition-colors hover:text-white">Outcomes</a></div><Link href="/sign-in" className="rounded-lg border border-white/10 bg-white/[0.06] px-4 py-2 text-sm font-medium transition hover:border-white/20 hover:bg-white/10">Sign in</Link></nav>
    <section className="relative mx-auto grid max-w-6xl gap-14 px-6 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-orange-400/20 bg-orange-400/10 px-3 py-1.5 text-xs font-medium text-orange-200"><span className="h-1.5 w-1.5 rounded-full bg-orange-400" /> Applications for the next cohort are open</div><h1 className="max-w-3xl text-5xl font-semibold leading-[1.03] tracking-[-0.055em] text-white sm:text-6xl lg:text-7xl">Build work that gets you <span className="text-orange-400">noticed.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-slate-300 sm:text-lg">A 60-day, portfolio-first challenge for ambitious engineering students. Build consistently, publish your progress, and create proof that opens doors.</p><p className="mt-4 text-sm text-slate-500">Made for future <span key={roleIndex} className="role-rise inline-block font-medium text-orange-300">{roles[roleIndex]}.</span></p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/dashboard" className="inline-flex items-center justify-center gap-2 rounded-lg bg-orange-500 px-5 py-3.5 text-sm font-semibold text-[#160b03] shadow-[0_12px_35px_rgba(249,115,22,.25)] transition hover:bg-orange-400">Join the next cohort <ArrowIcon /></Link><a href="#how-it-works" className="inline-flex items-center justify-center rounded-lg border border-white/10 px-5 py-3.5 text-sm font-medium text-slate-200 transition hover:bg-white/5">See how it works</a></div><div className="mt-10 flex items-center gap-4 text-sm text-slate-400"><div className="flex -space-x-2">{["AS", "NK", "PM", "RV"].map((initials, index) => <span key={initials} className={`grid h-8 w-8 place-items-center rounded-full border-2 border-[#090b12] text-[9px] font-bold ${index % 2 ? "bg-slate-700" : "bg-orange-500/80"}`}>{initials}</span>)}</div><span><strong className="font-semibold text-white">500+</strong> students building in public</span></div></div>
      <div className="relative mx-auto w-full max-w-[440px] rounded-2xl border border-white/10 bg-[#111520]/80 p-4 shadow-2xl shadow-black/30 backdrop-blur sm:p-5"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-sm font-semibold">Your 60-day sprint</p><p className="mt-1 text-xs text-slate-500">A small daily practice. A visible body of work.</p></div><span className="rounded-md bg-orange-400/10 px-2.5 py-1 text-xs font-medium text-orange-300">Day 23</span></div><div className="mt-5 rounded-xl border border-white/10 bg-[#0c0f17] p-4"><div className="flex items-center justify-between text-xs"><span className="text-slate-400">Challenge progress</span><span className="font-medium text-orange-300">38%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[38%] rounded-full bg-gradient-to-r from-orange-600 to-orange-300" /></div><div className="mt-5 flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-orange-400/10 text-sm font-bold text-orange-300">23</span><div><p className="text-sm font-medium">Build a REST API with Express</p><p className="mt-1 text-xs leading-5 text-slate-500">Ship a production-minded CRUD API and document your decisions.</p></div></div></div><div className="mt-4 grid grid-cols-3 gap-3">{[["23", "day streak"], ["06", "projects"], ["12%", "top cohort"]].map(([number, label]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[0.025] px-3 py-3"><p className="text-lg font-semibold tracking-tight text-white">{number}</p><p className="mt-0.5 text-[10px] text-slate-500">{label}</p></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-xl border border-orange-400/15 bg-orange-400/[0.06] p-3"><span className="h-2 w-2 rounded-full bg-orange-400" /><p className="text-xs text-orange-100/80">Today&apos;s work is ready when you are.</p></div></div></section>
    <section className="relative border-y border-white/[0.07] bg-white/[0.025]"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-y-8 px-6 py-9 sm:grid-cols-4 lg:px-8"><CountUpStat value={500} suffix="+" label="students enrolled" /><CountUpStat value={60} label="days of building" /><CountUpStat value={42} suffix="%" label="report more confidence" /><CountUpStat value={6} label="focused career tracks" /></div></section>
    <section id="how-it-works" className="relative mx-auto max-w-6xl px-6 py-24 lg:px-8"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-orange-300">The approach</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Less noise. More evidence of what you can do.</h2><p className="mt-4 leading-7 text-slate-400">The programme turns consistent effort into a portfolio that is easy for people to understand and hard to overlook.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{steps.map(([number, title, description]) => <article key={number} className="group rounded-xl border border-white/10 bg-[#0d1019] p-6 transition hover:-translate-y-1 hover:border-orange-400/30"><p className="text-sm font-medium text-orange-300">{number}</p><h3 className="mt-12 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><span className="mt-7 block h-px w-full bg-gradient-to-r from-orange-400/70 to-transparent" /></article>)}</div></section>
    <section id="tracks" className="border-y border-white/[0.07] bg-[#0c0f17]"><div className="mx-auto grid max-w-6xl gap-10 px-6 py-24 lg:grid-cols-[.7fr_1.3fr] lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-orange-300">Choose a direction</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">One challenge. Six paths.</h2><p className="mt-4 text-sm leading-6 text-slate-400">Start with the area you want to grow in. The system is built around focused practice, not generic content.</p></div><div className="grid gap-3 sm:grid-cols-2">{tracks.map((track, index) => <div key={track} className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[0.025] px-4 py-4 transition hover:border-orange-400/35 hover:bg-orange-400/[0.04]"><span className="text-sm font-medium text-slate-200">{track}</span><span className="text-xs text-slate-600">0{index + 1}</span></div>)}</div></div></section>
    <section id="outcomes" className="mx-auto max-w-6xl px-6 py-24 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-orange-300">Student outcomes</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Progress that speaks for itself.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-400">Stories from students who made consistency part of their career advantage.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{testimonials.map(([initials, name, college, quote]) => <figure key={name} className="rounded-xl border border-white/10 bg-white/[0.025] p-6"><blockquote className="text-base leading-7 text-slate-200">&ldquo;{quote}&rdquo;</blockquote><figcaption className="mt-8 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-orange-400/10 text-[10px] font-bold text-orange-300">{initials}</span><span><span className="block text-sm font-medium text-white">{name}</span><span className="block text-xs text-slate-500">{college}</span></span></figcaption></figure>)}</div></section>
    <section className="mx-6 mb-12 rounded-2xl border border-orange-400/20 bg-[radial-gradient(ellipse_at_top_right,rgba(249,115,22,.2),transparent_55%),#10131d] lg:mx-auto lg:max-w-6xl"><div className="grid gap-8 px-6 py-10 sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-medium text-orange-200">Next cohort starts soon</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Your next commit can change the trajectory.</h2></div><div className="flex gap-2">{Object.entries(timeLeft).map(([label, value]) => <div key={label} className="min-w-14 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-center"><p className="font-mono text-xl font-semibold text-white">{String(value).padStart(2, "0")}</p><p className="mt-1 text-[9px] font-medium uppercase tracking-wider text-slate-500">{label}</p></div>)}</div><Link href="/dashboard" className="inline-flex items-center justify-center gap-2 rounded-lg bg-orange-500 px-5 py-3.5 text-sm font-semibold text-[#160b03] transition hover:bg-orange-400 lg:col-span-2">Reserve your place <ArrowIcon /></Link></div></section>
    <footer className="border-t border-white/[0.07] py-8"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-6 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span className="font-medium text-slate-300">ABTalks</span><span>Built for engineers who want their work to be seen.</span><span>© 2026 ABTalks</span></div></footer>
  </main>;
}
